### ISSUE TITLE
Code Formatting is misleading

### ISSUE THREAD

**Issue by alefort** [jdoyle65/SifterAPI#3]
The following code in Sifter Class:

`return Sifter::curl()->getBaseUrl().self::PROJECTS_URL . $projectId;`

caused me great grief as I found myself trying to figure out how I didn't know you could reference 'self' from a function return via a period. Then I realized it was just the string concatenation operator.

If you're interested, you can greatly improve the readability of this line of code by adding some spaces:

`return Sifter::curl()->getBaseUrl() . self::PROJECTS_URL . $projectId;`

**Comment by jdoyle65** [comment]
Absolutely agree!
